// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JobOffersColumns holds the columns for the "job_offers" table.
	JobOffersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "file_url", Type: field.TypeString},
		{Name: "published_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// JobOffersTable holds the schema information for the "job_offers" table.
	JobOffersTable = &schema.Table{
		Name:       "job_offers",
		Columns:    JobOffersColumns,
		PrimaryKey: []*schema.Column{JobOffersColumns[0]},
	}
	// SearchInputsColumns holds the columns for the "search_inputs" table.
	SearchInputsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "search", Type: field.TypeString},
	}
	// SearchInputsTable holds the schema information for the "search_inputs" table.
	SearchInputsTable = &schema.Table{
		Name:       "search_inputs",
		Columns:    SearchInputsColumns,
		PrimaryKey: []*schema.Column{SearchInputsColumns[0]},
	}
	// SearchInputSearchResultsColumns holds the columns for the "search_input_search_results" table.
	SearchInputSearchResultsColumns = []*schema.Column{
		{Name: "search_input_id", Type: field.TypeInt},
		{Name: "job_offer_id", Type: field.TypeInt},
	}
	// SearchInputSearchResultsTable holds the schema information for the "search_input_search_results" table.
	SearchInputSearchResultsTable = &schema.Table{
		Name:       "search_input_search_results",
		Columns:    SearchInputSearchResultsColumns,
		PrimaryKey: []*schema.Column{SearchInputSearchResultsColumns[0], SearchInputSearchResultsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "search_input_search_results_search_input_id",
				Columns:    []*schema.Column{SearchInputSearchResultsColumns[0]},
				RefColumns: []*schema.Column{SearchInputsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "search_input_search_results_job_offer_id",
				Columns:    []*schema.Column{SearchInputSearchResultsColumns[1]},
				RefColumns: []*schema.Column{JobOffersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JobOffersTable,
		SearchInputsTable,
		SearchInputSearchResultsTable,
	}
)

func init() {
	SearchInputSearchResultsTable.ForeignKeys[0].RefTable = SearchInputsTable
	SearchInputSearchResultsTable.ForeignKeys[1].RefTable = JobOffersTable
}
