// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marianozunino/go-utu-llamados/ent/joboffer"
	"github.com/marianozunino/go-utu-llamados/ent/predicate"
	"github.com/marianozunino/go-utu-llamados/ent/searchinput"
)

// SearchInputQuery is the builder for querying SearchInput entities.
type SearchInputQuery struct {
	config
	ctx               *QueryContext
	order             []searchinput.OrderOption
	inters            []Interceptor
	predicates        []predicate.SearchInput
	withSearchResults *JobOfferQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SearchInputQuery builder.
func (siq *SearchInputQuery) Where(ps ...predicate.SearchInput) *SearchInputQuery {
	siq.predicates = append(siq.predicates, ps...)
	return siq
}

// Limit the number of records to be returned by this query.
func (siq *SearchInputQuery) Limit(limit int) *SearchInputQuery {
	siq.ctx.Limit = &limit
	return siq
}

// Offset to start from.
func (siq *SearchInputQuery) Offset(offset int) *SearchInputQuery {
	siq.ctx.Offset = &offset
	return siq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (siq *SearchInputQuery) Unique(unique bool) *SearchInputQuery {
	siq.ctx.Unique = &unique
	return siq
}

// Order specifies how the records should be ordered.
func (siq *SearchInputQuery) Order(o ...searchinput.OrderOption) *SearchInputQuery {
	siq.order = append(siq.order, o...)
	return siq
}

// QuerySearchResults chains the current query on the "search_results" edge.
func (siq *SearchInputQuery) QuerySearchResults() *JobOfferQuery {
	query := (&JobOfferClient{config: siq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := siq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := siq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(searchinput.Table, searchinput.FieldID, selector),
			sqlgraph.To(joboffer.Table, joboffer.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, searchinput.SearchResultsTable, searchinput.SearchResultsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(siq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SearchInput entity from the query.
// Returns a *NotFoundError when no SearchInput was found.
func (siq *SearchInputQuery) First(ctx context.Context) (*SearchInput, error) {
	nodes, err := siq.Limit(1).All(setContextOp(ctx, siq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{searchinput.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (siq *SearchInputQuery) FirstX(ctx context.Context) *SearchInput {
	node, err := siq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SearchInput ID from the query.
// Returns a *NotFoundError when no SearchInput ID was found.
func (siq *SearchInputQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = siq.Limit(1).IDs(setContextOp(ctx, siq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{searchinput.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (siq *SearchInputQuery) FirstIDX(ctx context.Context) int {
	id, err := siq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SearchInput entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SearchInput entity is found.
// Returns a *NotFoundError when no SearchInput entities are found.
func (siq *SearchInputQuery) Only(ctx context.Context) (*SearchInput, error) {
	nodes, err := siq.Limit(2).All(setContextOp(ctx, siq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{searchinput.Label}
	default:
		return nil, &NotSingularError{searchinput.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (siq *SearchInputQuery) OnlyX(ctx context.Context) *SearchInput {
	node, err := siq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SearchInput ID in the query.
// Returns a *NotSingularError when more than one SearchInput ID is found.
// Returns a *NotFoundError when no entities are found.
func (siq *SearchInputQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = siq.Limit(2).IDs(setContextOp(ctx, siq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{searchinput.Label}
	default:
		err = &NotSingularError{searchinput.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (siq *SearchInputQuery) OnlyIDX(ctx context.Context) int {
	id, err := siq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SearchInputs.
func (siq *SearchInputQuery) All(ctx context.Context) ([]*SearchInput, error) {
	ctx = setContextOp(ctx, siq.ctx, "All")
	if err := siq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SearchInput, *SearchInputQuery]()
	return withInterceptors[[]*SearchInput](ctx, siq, qr, siq.inters)
}

// AllX is like All, but panics if an error occurs.
func (siq *SearchInputQuery) AllX(ctx context.Context) []*SearchInput {
	nodes, err := siq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SearchInput IDs.
func (siq *SearchInputQuery) IDs(ctx context.Context) (ids []int, err error) {
	if siq.ctx.Unique == nil && siq.path != nil {
		siq.Unique(true)
	}
	ctx = setContextOp(ctx, siq.ctx, "IDs")
	if err = siq.Select(searchinput.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (siq *SearchInputQuery) IDsX(ctx context.Context) []int {
	ids, err := siq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (siq *SearchInputQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, siq.ctx, "Count")
	if err := siq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, siq, querierCount[*SearchInputQuery](), siq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (siq *SearchInputQuery) CountX(ctx context.Context) int {
	count, err := siq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (siq *SearchInputQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, siq.ctx, "Exist")
	switch _, err := siq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (siq *SearchInputQuery) ExistX(ctx context.Context) bool {
	exist, err := siq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SearchInputQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (siq *SearchInputQuery) Clone() *SearchInputQuery {
	if siq == nil {
		return nil
	}
	return &SearchInputQuery{
		config:            siq.config,
		ctx:               siq.ctx.Clone(),
		order:             append([]searchinput.OrderOption{}, siq.order...),
		inters:            append([]Interceptor{}, siq.inters...),
		predicates:        append([]predicate.SearchInput{}, siq.predicates...),
		withSearchResults: siq.withSearchResults.Clone(),
		// clone intermediate query.
		sql:  siq.sql.Clone(),
		path: siq.path,
	}
}

// WithSearchResults tells the query-builder to eager-load the nodes that are connected to
// the "search_results" edge. The optional arguments are used to configure the query builder of the edge.
func (siq *SearchInputQuery) WithSearchResults(opts ...func(*JobOfferQuery)) *SearchInputQuery {
	query := (&JobOfferClient{config: siq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	siq.withSearchResults = query
	return siq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Search string `json:"search,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SearchInput.Query().
//		GroupBy(searchinput.FieldSearch).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (siq *SearchInputQuery) GroupBy(field string, fields ...string) *SearchInputGroupBy {
	siq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SearchInputGroupBy{build: siq}
	grbuild.flds = &siq.ctx.Fields
	grbuild.label = searchinput.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Search string `json:"search,omitempty"`
//	}
//
//	client.SearchInput.Query().
//		Select(searchinput.FieldSearch).
//		Scan(ctx, &v)
func (siq *SearchInputQuery) Select(fields ...string) *SearchInputSelect {
	siq.ctx.Fields = append(siq.ctx.Fields, fields...)
	sbuild := &SearchInputSelect{SearchInputQuery: siq}
	sbuild.label = searchinput.Label
	sbuild.flds, sbuild.scan = &siq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SearchInputSelect configured with the given aggregations.
func (siq *SearchInputQuery) Aggregate(fns ...AggregateFunc) *SearchInputSelect {
	return siq.Select().Aggregate(fns...)
}

func (siq *SearchInputQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range siq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, siq); err != nil {
				return err
			}
		}
	}
	for _, f := range siq.ctx.Fields {
		if !searchinput.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if siq.path != nil {
		prev, err := siq.path(ctx)
		if err != nil {
			return err
		}
		siq.sql = prev
	}
	return nil
}

func (siq *SearchInputQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SearchInput, error) {
	var (
		nodes       = []*SearchInput{}
		_spec       = siq.querySpec()
		loadedTypes = [1]bool{
			siq.withSearchResults != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SearchInput).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SearchInput{config: siq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, siq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := siq.withSearchResults; query != nil {
		if err := siq.loadSearchResults(ctx, query, nodes,
			func(n *SearchInput) { n.Edges.SearchResults = []*JobOffer{} },
			func(n *SearchInput, e *JobOffer) { n.Edges.SearchResults = append(n.Edges.SearchResults, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (siq *SearchInputQuery) loadSearchResults(ctx context.Context, query *JobOfferQuery, nodes []*SearchInput, init func(*SearchInput), assign func(*SearchInput, *JobOffer)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*SearchInput)
	nids := make(map[int]map[*SearchInput]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(searchinput.SearchResultsTable)
		s.Join(joinT).On(s.C(joboffer.FieldID), joinT.C(searchinput.SearchResultsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(searchinput.SearchResultsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(searchinput.SearchResultsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*SearchInput]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*JobOffer](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "search_results" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (siq *SearchInputQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := siq.querySpec()
	_spec.Node.Columns = siq.ctx.Fields
	if len(siq.ctx.Fields) > 0 {
		_spec.Unique = siq.ctx.Unique != nil && *siq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, siq.driver, _spec)
}

func (siq *SearchInputQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(searchinput.Table, searchinput.Columns, sqlgraph.NewFieldSpec(searchinput.FieldID, field.TypeInt))
	_spec.From = siq.sql
	if unique := siq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if siq.path != nil {
		_spec.Unique = true
	}
	if fields := siq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, searchinput.FieldID)
		for i := range fields {
			if fields[i] != searchinput.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := siq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := siq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := siq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := siq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (siq *SearchInputQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(siq.driver.Dialect())
	t1 := builder.Table(searchinput.Table)
	columns := siq.ctx.Fields
	if len(columns) == 0 {
		columns = searchinput.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if siq.sql != nil {
		selector = siq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if siq.ctx.Unique != nil && *siq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range siq.predicates {
		p(selector)
	}
	for _, p := range siq.order {
		p(selector)
	}
	if offset := siq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := siq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SearchInputGroupBy is the group-by builder for SearchInput entities.
type SearchInputGroupBy struct {
	selector
	build *SearchInputQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sigb *SearchInputGroupBy) Aggregate(fns ...AggregateFunc) *SearchInputGroupBy {
	sigb.fns = append(sigb.fns, fns...)
	return sigb
}

// Scan applies the selector query and scans the result into the given value.
func (sigb *SearchInputGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sigb.build.ctx, "GroupBy")
	if err := sigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SearchInputQuery, *SearchInputGroupBy](ctx, sigb.build, sigb, sigb.build.inters, v)
}

func (sigb *SearchInputGroupBy) sqlScan(ctx context.Context, root *SearchInputQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sigb.fns))
	for _, fn := range sigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sigb.flds)+len(sigb.fns))
		for _, f := range *sigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SearchInputSelect is the builder for selecting fields of SearchInput entities.
type SearchInputSelect struct {
	*SearchInputQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sis *SearchInputSelect) Aggregate(fns ...AggregateFunc) *SearchInputSelect {
	sis.fns = append(sis.fns, fns...)
	return sis
}

// Scan applies the selector query and scans the result into the given value.
func (sis *SearchInputSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sis.ctx, "Select")
	if err := sis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SearchInputQuery, *SearchInputSelect](ctx, sis.SearchInputQuery, sis, sis.inters, v)
}

func (sis *SearchInputSelect) sqlScan(ctx context.Context, root *SearchInputQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sis.fns))
	for _, fn := range sis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
