// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marianozunino/go-utu-llamados/ent/predicate"
	"github.com/marianozunino/go-utu-llamados/ent/searchinput"
)

// SearchInputDelete is the builder for deleting a SearchInput entity.
type SearchInputDelete struct {
	config
	hooks    []Hook
	mutation *SearchInputMutation
}

// Where appends a list predicates to the SearchInputDelete builder.
func (sid *SearchInputDelete) Where(ps ...predicate.SearchInput) *SearchInputDelete {
	sid.mutation.Where(ps...)
	return sid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sid *SearchInputDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sid.sqlExec, sid.mutation, sid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sid *SearchInputDelete) ExecX(ctx context.Context) int {
	n, err := sid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sid *SearchInputDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(searchinput.Table, sqlgraph.NewFieldSpec(searchinput.FieldID, field.TypeInt))
	if ps := sid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sid.mutation.done = true
	return affected, err
}

// SearchInputDeleteOne is the builder for deleting a single SearchInput entity.
type SearchInputDeleteOne struct {
	sid *SearchInputDelete
}

// Where appends a list predicates to the SearchInputDelete builder.
func (sido *SearchInputDeleteOne) Where(ps ...predicate.SearchInput) *SearchInputDeleteOne {
	sido.sid.mutation.Where(ps...)
	return sido
}

// Exec executes the deletion query.
func (sido *SearchInputDeleteOne) Exec(ctx context.Context) error {
	n, err := sido.sid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{searchinput.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sido *SearchInputDeleteOne) ExecX(ctx context.Context) {
	if err := sido.Exec(ctx); err != nil {
		panic(err)
	}
}
