// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// JobOffer is the predicate function for joboffer builders.
type JobOffer func(*sql.Selector)

// SearchInput is the predicate function for searchinput builders.
type SearchInput func(*sql.Selector)
